### ISSUE TITLE
Grey not properly syntax hilighted

### ISSUE THREAD

**Issue by erickramirez** [atom/language-css#32]
This is super small, but *grey* isn't properly syntax highlighted / recognized as a valid color value ([which it is](http://www.w3.org/TR/css3-color/#grey)).

I don't think it's super relevant, but I am using Atom 1.0 on Windows 8.

![error](https://cloud.githubusercontent.com/assets/4407518/8491579/c29d4a9e-2109-11e5-84e1-bbd84845a270.png)

**Comment by kubetz** [comment]
Not sure what is going on, but when I tried to reproduce it in safe-mode I had both `gray` and `grey` recognized as colors.

![grey](https://cloud.githubusercontent.com/assets/1128248/8496891/03d2623c-2179-11e5-927e-0550350717ac.png)

**Comment by kubetz** [comment]
@erickramirez Is this still not working for you? Have you tried running atom in safe mode with `atom --safe`? Are you sure your grammar is set to `CSS`?

I tried normal and safe mode and it works. Also according to the [source code](https://github.com/atom/language-css/blob/master/grammars/css.cson#L215) it should work too.

`grey` is not working using *SASS or SCSS grammar*, but not because it is not recognized, but it is marked as `invalid deprecated color w3c-non-standard-color-name`. It is also not a part of `language-css` package.

![grey](https://cloud.githubusercontent.com/assets/1128248/8530351/d535ad62-2420-11e5-8e65-10f89564f5e0.png)

**Comment by erickramirez** [comment]
Ahhh, that's right, I was using SCSS. Sorry for the issue then.
