### ISSUE TITLE
Colon Spacing Setting

### ISSUE THREAD

**Issue by refringe** [atom/language-css#49]
I would love to have the option to adjust the spacing around the colon (:) between CSS properties and values. I think the setting is currently hard-coded in:
![Example](https://cloud.githubusercontent.com/assets/6096539/4251730/bc0bb5e6-3a8f-11e4-887a-ee3ffe988aae.gif)

There is no "proper" way to have this formatted; it's simply preference. Personally I prefer to have no space: `background:url(img.jpg);`

I'm not the only one:
atom/autocomplete-plus#103

Also in the autocomplete-plus issue above they mention that this should be an option in the "autocomplete-plus providers", so I hope I'm in the right place?

**Comment by jenniferaslan** [comment]
I agree. I don't want a space after the colon. Since I don't have each property on its own line in the code, I rely on the space after the semicolon to show me where they begin and end, and having a space after the colon messes up my ability to visually scan the file for what I'm looking for. Please add an option for whether you want the space after the colon on autocomplete or not. Thanks.

**Comment by 50Wliu** [comment]
Hey @refringe, sorry for the delay in replying.  The autocompletion provide for language-css is actually autocomplete-css - would you mind moving this issue over there?  Thanks.
